### ISSUE TITLE
Windows binary missing

### ISSUE THREAD

**Issue by thisismygitrepo** [sudipghimire533/ytui-music#44]
README talks about Windows support but the release only shows excutables for MacOS & Linux.

**Comment by CB61-A1** [comment]
You'll need to compile it from source. It's really simple, just do this:

[Rust Install (Follow the guide)](https://www.rust-lang.org/tools/install)
Once you get it download the [source].(https://github.com/sudipghimire533/ytui-music/archive/refs/heads/main.zip)
Now you can compile it:
```cargo build --all --release```
You can also add it to $PATH but I'm not too sure how to do it on windows. I'm guessing you go to Edit Environment Variables and add the executable but I don't know.

**Comment by thisismygitrepo** [comment]
Failed here:

```shell
   Compiling http-body v0.4.5
error: failed to run custom build command for `libsqlite3-sys v0.25.2`

Caused by:
  process didn't exit successfully: `C:\Users\aalsaf01\Downloads\ytui-music-main\ytui-music-main\target\release\build\libsqlite3-sys-3d2c346e56dbaecf\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Could not copy bindings to output directory: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', C:\Users\aalsaf01\.cargo\registry\src\github.com-1ecc6299db9ec823\libsqlite3-sys-0.25.2\build.rs:102:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

To be honest, if never done, its too confident to claim that it works on Windows. I would definitely remove it from README until verified.

**Comment by emmanuelwithme** [comment]
> Failed here:
> 
> ```shell
>    Compiling http-body v0.4.5
> error: failed to run custom build command for `libsqlite3-sys v0.25.2`
> 
> Caused by:
>   process didn't exit successfully: `C:\Users\aalsaf01\Downloads\ytui-music-main\ytui-music-main\target\release\build\libsqlite3-sys-3d2c346e56dbaecf\build-script-build` (exit code: 101)
>   --- stderr
>   thread 'main' panicked at 'Could not copy bindings to output directory: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', C:\Users\aalsaf01\.cargo\registry\src\github.com-1ecc6299db9ec823\libsqlite3-sys-0.25.2\build.rs:102:18
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> ```

Same problem as yours.

**Comment by chokgok** [comment]
This might not be any help, but I recommend using Windows Subsystem for Linux. You can use any Linux distribution in the Windows Terminal and install any Linux packages+programs.

**Comment by Tryoskasen** [comment]
I solved it just delete winsqlite3 on config/cargo.toml

`[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "4.0"
lazy_static = "1.4.0"
rand = "0.8"
rusqlite = { version = "0.28", features = ["bundled", "extra_check", "winsqlite3" -> delete this] }`

but another problem is need mpv.lib. possible to solve it as said [https://github.com/sudipghimire533/ytui-music/issues/47#issuecomment-2466440477](url)
